#ifndef FSP_H
#define FSP_H

enum ProgramState
{
    PROGRAM_STATE_START,
    PROGRAM_STATE_EXIT,
    PROGRAM_STATE_SOLVE,
    PROGRAM_STATE_A,
    PROGRAM_STATE_B,
    PROGRAM_STATE_C,
    PROGRAM_STATE_MEOW,
};

#endif // FSP_H
